### ISSUE TITLE
init : 초기 설정

### ISSUE THREAD

**Issue by seojin-kim12** [PPiyongpiyong/Front-end#1]
## #️⃣연관된 이슈

> #1 (초기 설정)

## 📝작업 내용

> 프로젝트의 기본 틀을 설정함
> 이번 작업에서는 개발 환경을 설정하고 필수적인 라이브러리를 설치함
>
> - 프로젝트 초기화 (`create-react-app` 또는 프로젝트 구조 생성)
> - 필수 라이브러리 설치:
>   - `react-router-dom`
>   - `framer-motion`
>   - `styled-components`
> - ESLint 및 Prettier 설정
> - 폴더 구조 설정 (`src/pages` 등)
> 
> 추가적으로, 프로젝트 실행 테스트 완료.

### 스크린샷 (선택)

>![image](https://github.com/user-attachments/assets/b2979562-7282-400f-b62e-d8f1a87c26e7)

## 💬리뷰 요구사항(선택)

> 초기 폴더 구조나 추가적으로 설정해야 할 환경 요소 있으면 연락 주세요~

**Comment by Chaejy** [comment]
좋아요~ 고생하셨습니다 devlop 브랜치로 pr해주세요~~!
